<?php
/**
 * @Author: k_nguyen
 * @Date:   2016-11-14 11:24:17
 * @Last Modified by:   k_nguyen
 * @Last Modified time: 2017-07-06 09:57:49
 */
namespace Client;
use \Controller\Exception;

class Controller_Export extends \Controller_Common {
	public function before() {
        parent::before();
        if(!\Package::loaded('excel')){
            \Package::load("excel");
        }
        
        $this->formatTitleHeader = ['font' => [
                                        'name' => 'Times New Roman',
                                        'bold' => true,
                                        'italic' => false,
                                        'size' => 10,
                                        'color' => ['rgb'=>  \PHPExcel_Style_Color::COLOR_WHITE]
                                    ],
                                    'alignment' => [
                                        'horizontal' =>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                                        'vertical' => \PHPExcel_Style_Alignment::VERTICAL_CENTER,
                                        'wrap' => false
                                    ]];
    }

    /*=============================================================
     * Author: Nguyen Anh Khoa
     * Action export list user
     *=============================================================*/
    public function action_list_user(){
        $param = \Input::param();
        $export_date = isset($param['export_date'])?date('Y-m-d', strtotime($param['export_date'])):date('Y-m-d');

        $bank_account_type_code = ['1' => '普通', '2' => '当座'];
        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->getProperties()->setCreator('Vision')
                                        ->setLastModifiedBy('Vision')
                                        ->setTitle('Office 2007 Document')
                                        ->setSubject('Office 2007 Document')
                                        ->setDescription('Document has been generated by PHP')
                                        ->setKeywords('Office 2007 openxml php')
                                        ->setCategory('Route File');
        $header = ['社員No', //staff_no
                    '社員名', //full_name
                    '社員名(カナ)', //full_name_kana
                    '入社年月日', // entry_day
                    '退職年月日', // retirement_date
                    'ユーザID', //user_id
                    'メールアドレス', //email
                    '会社名', // company_name
                    '部門コード', // department_code
                    '事業本部', // bisiness_division_name
                    '事業部', // division_name
                    '部門', //department_name
                    '役職', //post_name
                    '銀行', //bank_name
                    '支店', //bank_branch_name
                    '口座番号', //bank_account_no
                    '口座種類', //bank_account_type_code
                    '名義人', //bank_account_holder
                    '適用開始日', //enable_start_date
                    '適用終了日', //enable_end_date
                    '兼任' // concurrent_post_flg
                    ];
        $last_column = null;
        foreach($header as $i=>$v){
            $column = \PHPExcel_Cell::stringFromColumnIndex($i);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($column.'1',$v);
            $objPHPExcel->getActiveSheet()->getStyle($column.'1')->applyFromArray($this->formatTitleHeader);
            switch($i+1){
                case 7:
                    $width = 35;
                    break;
                case 6:
                case 8:
                    $width = 20;
                    break;
                case 11:
                case 12:
                case 18:
                    $width = 30;
                    break;
                case 13:
                    $width = 23;
                    break;
                default:
                    $width = 16;
                    break;
            }    
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth($width);
            $last_column = $column;
        }   
       
        /*====================================
         * Get list user has department enable_start_date >= export day <= enable_end_date
         * Or enable_start_date >= export day && enable_end_date IS NULL
         *====================================*/
        $query = \DB::select('MUD.*', 'MU.*',
                    \DB::expr('MC.name AS company_name'), \DB::expr('BUS.name AS business_name'), \DB::expr('DIV.name AS division_name'),
                    \DB::expr('DEP.name AS department_name'), \DB::expr('DEP.code AS department_code'), \DB::expr('MP.name AS position_name'),
                    \DB::expr('MB.name AS bank_name'), \DB::expr('MBB.name AS bank_branch_name'))
                    ->from(['m_user_department', 'MUD'])
                    ->join(['m_user', 'MU'], 'left')->on('MUD.m_user_id', '=', 'MU.id')

                    ->join(['m_department', 'DEP'], 'left')->on('DEP.id', '=', 'MUD.m_department_id')->on('DEP.level', '=', \DB::expr(3))
                    ->join(['m_department', 'DIV'], 'left')->on('DIV.id', '=', 'DEP.parent')->on('DIV.level', '=', \DB::expr(2))
                    ->join(['m_department', 'BUS'], 'left')->on('BUS.id', '=', 'DIV.parent')->on('BUS.level', '=', \DB::expr(1))
                    ->join(['m_company', 'MC'], 'left')->on('MC.id', '=', 'BUS.m_company_id')
                    ->join(['m_position', 'MP'], 'left')->on('MP.id', '=', 'MUD.m_position_id')
                    ->join(['m_bank', 'MB'], 'left')->on('MB.id', '=', 'MU.m_bank_id')
                    ->join(['m_bank_branch', 'MBB'], 'left')->on('MBB.id', '=', 'MU.m_bank_branch_id')

                    ->where('MU.item_status', '=', 'active')
                    ->and_where('MUD.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('MUD.enable_start_date'), \DB::expr('MUD.enable_end_date')])
                        ->or_where_open()
                            ->and_where(\DB::expr('MUD.enable_start_date'), '<=', $export_date)
                            ->and_where(\DB::expr('MUD.enable_end_date'), 'IS', \DB::expr('NULL'))
                        ->or_where_close()
                    ->and_where_close()

                    ->and_where('DEP.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('DEP.enable_start_date'), \DB::expr('DEP.enable_end_date')])
                        ->or_where_open()
                            ->and_where(\DB::expr('DEP.enable_start_date'), '<=', $export_date)
                            ->and_where(\DB::expr('DEP.enable_end_date'), 'IS', \DB::expr('NULL'))
                        ->or_where_close()
                    ->and_where_close()
                    ->order_by('MU.staff_no', 'ASC');
        $users = $query->execute()->as_array();
        $i = $row = 0;
        foreach($users as $user){
            $row = $i+2;
            $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row,$user['staff_no'])
                                            ->setCellValue('B'.$row,$user['fullname'])
                                            ->setCellValue('C'.$row,$user['fullname_kana'])
                                            ->setCellValue('D'.$row,$user['entry_date']?\Vision_Common::system_format_date(strtotime($user['entry_date'])):null)
                                            ->setCellValue('E'.$row,$user['retirement_date']?\Vision_Common::system_format_date(strtotime($user['retirement_date'])):null)
                                            ->setCellValue('F'.$row,$user['user_id'])
                                            ->setCellValue('G'.$row,$user['email'])
                                            ->setCellValue('H'.$row,$user['company_name'])
                                            ->setCellValue('I'.$row,$user['department_code'])
                                            ->setCellValue('J'.$row,$user['business_name'])
                                            ->setCellValue('K'.$row,$user['division_name'])
                                            ->setCellValue('L'.$row,$user['department_name'])
                                            ->setCellValue('M'.$row,$user['position_name'])
                                            ->setCellValue('N'.$row,$user['bank_name'])
                                            ->setCellValue('O'.$row,$user['bank_branch_name'])
                                            ->setCellValue('P'.$row,$user['bank_account_no'])
                                            ->setCellValue('Q'.$row,@$bank_account_type_code[$user['bank_account_type_code']])
                                            ->setCellValue('R'.$row,$user['bank_account_holder'])
                                            ->setCellValue('S'.$row,$user['enable_start_date']?\Vision_Common::system_format_date(strtotime($user['enable_start_date'])):null)
                                            ->setCellValue('T'.$row,$user['enable_end_date']?\Vision_Common::system_format_date(strtotime($user['enable_end_date'])):null)
                                            ->setCellValue('U'.$row,$user['concurrent_post_flag']?'兼任':null);
            $i++;
        }

        $format = ['alignment'=>array('horizontal'=>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,'wrap'=>true)];
        $objPHPExcel->getActiveSheet()->getStyle('A1:U1')->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('A1:U1')->getFill()->getStartColor()->setRGB('25a9cb');

        header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
        header("Cache-Control: max-age=0");
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="Users-'.$export_date.'.xls"');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit;          
        return \Response::forge();
    }

    /*=============================================================
     * Author: Nguyen Anh Khoa
     * Action export list user
     *=============================================================*/
    public function action_list_approval_department(){

        $param = \Input::param();
        $export_date = isset($param['export_date'])?date('Y-m-d', strtotime($param['export_date'])):date('Y-m-d');

        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->getProperties()->setCreator('Vision')
                                        ->setLastModifiedBy('Vision')
                                        ->setTitle('Office 2007 Document')
                                        ->setSubject('Office 2007 Document')
                                        ->setDescription('Document has been generated by PHP')
                                        ->setKeywords('Office 2007 openxml php')
                                        ->setCategory('Route File');

        $header = ['事業本部コード','事業本部','事業部コード','事業部','部門コード','部門', '適用開始日', '適用終了日','第1 承認者','第2 承認者','第3 承認者','第4 承認者','第5 承認者','第6 承認者','第7 承認者','第8 承認者','第9 承認者'];
        $last_column = null;
        foreach($header as $i=>$v){
            $column = \PHPExcel_Cell::stringFromColumnIndex($i);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($column.'1',$v);
            $objPHPExcel->getActiveSheet()->getStyle($column.'1')
                ->applyFromArray([
                    'font' => [
                        'name' => 'Times New Roman',
                        'bold' => true,
                        'italic' => false,
                        'size' => 10,
                        'color' => ['rgb'=>  \PHPExcel_Style_Color::COLOR_WHITE]
                    ],
                    'alignment' => [
                        'horizontal' =>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                        'vertical' => \PHPExcel_Style_Alignment::VERTICAL_CENTER,
                        'wrap' => false
                    ]
                ]);
            switch($i+1){
                case 1:
                case 3:
                case 5:
                    $width = 10;
                    break;
                case 2:
                    $width = 18;
                    break;
                case 4:
                case 6:
                    $width = 30;
                    break;
                default:
                    $width = 20;
                    break;
            }
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth($width);
            $last_column = $column;
        }
       
        /*====================================
         * Get list user has department enable_start_date >= export day <= enable_end_date
         * Or enable_start_date >= export day && enable_end_date IS NULL
         *====================================*/
        $query = \DB::select('MAD.*',
                    \DB::expr('BUS.code AS business_code'), \DB::expr('BUS.name AS business_name'), 
                    \DB::expr('DIV.code AS division_code'),\DB::expr('DIV.name AS division_name'),
                    \DB::expr('DEP.name AS department_name'), \DB::expr('DEP.code AS department_code'), \DB::expr('DEP.sub_code AS department_sub_code'))
                    ->from(['m_approval_department', 'MAD'])
                    ->join(['m_department', 'DEP'], 'left')->on('DEP.id', '=', 'MAD.m_department_id')->on('DEP.level', '=', \DB::expr(3))
                    ->join(['m_department', 'DIV'], 'left')->on('DIV.id', '=', 'DEP.parent')->on('DIV.level', '=', \DB::expr(2))
                    ->join(['m_department', 'BUS'], 'left')->on('BUS.id', '=', 'DIV.parent')->on('BUS.level', '=', \DB::expr(1))
                    ->where('MAD.item_status', '=', 'active')
                    ->where('DEP.allow_export_routes', '=', 1)

                    ->and_where('DEP.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('DEP.enable_start_date'), \DB::expr('DEP.enable_end_date')])
                        ->or_where_open()
                            ->and_where(\DB::expr('DEP.enable_start_date'), '<=', $export_date)
                            ->and_where(\DB::expr('DEP.enable_end_date'), 'IS', \DB::expr('NULL'))
                        ->or_where_close()
                    ->and_where_close()
                    
                    ->and_where('MAD.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('MAD.enable_start_date'), \DB::expr('MAD.enable_end_date')])
                        ->or_where_open()
                            ->and_where(\DB::expr('MAD.enable_start_date'), '<=', $export_date)
                            ->and_where(\DB::expr('MAD.enable_end_date'), 'IS', \DB::expr('NULL'))
                        ->or_where_close()
                    ->and_where_close()

                    ->group_by('MAD.m_department_id', 'MAD.enable_start_date')
                    ;
        $items = $query->execute()->as_array();
        
        
        //set content
        $i = 0;
        foreach($items as $item){
            $row = $i+2;
            // \Vision_Common::system_format_date(strtotime($user['entry_date'])):null)
            $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row,$item['business_code'])
                                            ->setCellValue('B'.$row,$item['business_name'])
                                            ->setCellValue('C'.$row,$item['division_code'])
                                            ->setCellValue('D'.$row,$item['division_name'])
                                            ->setCellValue('E'.$row,$item['department_code'])
                                            ->setCellValue('F'.$row,$item['department_name'])
                                            ->setCellValue('G'.$row,$item['enable_start_date']?\Vision_Common::system_format_date(strtotime($item['enable_start_date'])):null)
                                            ->setCellValue('H'.$row,$item['enable_end_date']?\Vision_Common::system_format_date(strtotime($item['enable_end_date'])):null)
                                            ;

            //Get user of routes
            $query = \DB::select('MU.fullname')
                    ->from(['m_user', 'MU'])
                    ->join(['m_approval_department', 'MAD'], 'left')->on('MAD.m_user_id', '=', 'MU.id')
                    ->where('MU.item_status', '=', 'active')
                    ->and_where('MAD.item_status', '=', 'active')
                    ->and_where('MAD.m_department_id', '=', $item['m_department_id'])
                    ->and_where('MAD.enable_start_date', '=', $item['enable_start_date'])
                    ->order_by('MAD.order', 'ASC')
                    ;
            $users = $query->execute()->as_array();     
            if(!empty($users)){
                $col = 8;
                foreach ($users as $user) {
                    $objPHPExcel->setActiveSheetIndex()->setCellValue(\PHPExcel_Cell::stringFromColumnIndex($col).$row,$user['fullname']);
                    $col++;
                }
            }

            $i++;
        }


        $format = ['alignment'=>array('horizontal'=>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,'wrap'=>true)];
        $objPHPExcel->getActiveSheet()->getStyle('A1:U1')->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('A1:U1')->getFill()->getStartColor()->setRGB('25a9cb');

        header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
        header("Cache-Control: max-age=0");
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="決裁経路（組織）-'.$export_date.'.xls"');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit;          
    }

    /*=============================================================
     * Author: Nguyen Anh Khoa
     * Action export list user table m_approval_menu
     *=============================================================*/
    public function action_list_approval_menu(){
        $param = \Input::param();
        $export_date = isset($param['export_date'])?date('Y-m-d', strtotime($param['export_date'])):date('Y-m-d');

        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->getProperties()->setCreator('Vision')
                                        ->setLastModifiedBy('Vision')
                                        ->setTitle('Office 2007 Document')
                                        ->setSubject('Office 2007 Document')
                                        ->setDescription('Document has been generated by PHP')
                                        ->setKeywords('Office 2007 openxml php')
                                        ->setCategory('Route File');

        $header = ['様式', '適用開始日', '適用終了日',
                    '第1 承認者','第1 承認者の権限',
                    '第2 承認者','第2 承認者の権限','第3 承認者','第3 承認者の権限',
                    '第4 承認者','第4 承認者の権限','第5 承認者','第5 承認者の権限',
                    '第6 承認者','第6 承認者の権限','第7 承認者','第7 承認者の権限',
                    '第8 承認者','第8 承認者の権限','第9 承認者','第9 承認者の権限',
                    '第10 承認者','第10 承認者の権限','第11 承認者','第11 承認者の権限',
                    '第12 承認者','第12 承認者の権限','第13 承認者','第13 承認者の権限',
                    '第14 承認者','第14 承認者の権限','第15 承認者','第15 承認者の権限',
                    ];
        $last_column = null;
        foreach($header as $i=>$v){
            $column = \PHPExcel_Cell::stringFromColumnIndex($i);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($column.'1',$v);
            $objPHPExcel->getActiveSheet()->getStyle($column.'1')
                ->applyFromArray([
                    'font' => [
                        'name' => 'Times New Roman',
                        'bold' => true,
                        'italic' => false,
                        'size' => 10,
                        'color' => ['rgb'=>  \PHPExcel_Style_Color::COLOR_WHITE]
                    ],
                    'alignment' => [
                        'horizontal' =>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                        'vertical' => \PHPExcel_Style_Alignment::VERTICAL_CENTER,
                        'wrap' => false
                    ]
                ]);
            switch($i+1){
                case 1:
                    $width = 50;
                    break;
                case 5: case 7: case 9: case 11: case 13:
                case 15: case 17: case 19: case 21: case 23: case 25:
                case 27: case 29: case 31: case 33: case 35: case 37: case 39: 
                    $width = 20;
                    break;
                default:
                    $width = 30;
                    break;
            }
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth($width);
            $last_column = $column;
        }
       
        /*====================================
         * Get list user has department enable_start_date >= export day <= enable_end_date
         * Or enable_start_date >= export day && enable_end_date IS NULL
         *====================================*/
        $query = \DB::select('MAM.*',
                    \DB::expr('MM.name AS menu_name'), \DB::expr('MM.id AS menu_id'), 
                    \DB::expr('MRM.name AS request_menu_name'), \DB::expr('MRM.id AS request_menu_id'))
                    ->from(['m_approval_menu', 'MAM'])
                    ->join(['m_menu', 'MM'], 'left')->on('MM.id', '=', 'MAM.m_menu_id')
                        ->on('MAM.petition_type', '=', \DB::expr("1"))
                        ->on('MM.item_status', '=', \DB::expr("'active'"))->on('MM.enable_flg', '=', \DB::expr("1"))
                    ->join(['m_request_menu', 'MRM'], 'left')->on('MRM.id', '=', 'MAM.m_menu_id')
                        ->on('MAM.petition_type', '=', \DB::expr("2"))
                        ->on('MRM.item_status', '=', \DB::expr("'active'"))->on('MRM.enable_flg', '=', \DB::expr("1"))
                    ->where('MAM.item_status', '=', 'active')
                    ->group_by('MAM.m_menu_id', 'MAM.petition_type', 'MAM.enable_start_date')
                    ;
        $items = $query->execute()->as_array();
        
        //set content
        $i = 0;
        foreach($items as $item){
            $row = $i+2;
            switch ($item['petition_type']) {
                case 1:
                    $menu_name = $item['menu_name'];
                    $menu_id = $item['menu_id'];
                    break;
                case 2:
                    $menu_name = $item['request_menu_name'];
                    $menu_id = $item['request_menu_id'];
                    break;
            }

            if(empty($menu_id)) continue;
            $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row, $menu_name)
                                                ->setCellValue('B'.$row,$item['enable_start_date']?\Vision_Common::system_format_date(strtotime($item['enable_start_date'])):null)
                                                ->setCellValue('C'.$row,$item['enable_end_date']?\Vision_Common::system_format_date(strtotime($item['enable_end_date'])):null);

            //Get user of routes
            $query = \DB::select('MU.fullname', \DB::expr('MA.name AS authority_name'))
                    ->from(['m_user', 'MU'])
                    // ->join(['m_user_department', 'MUD'], 'left')->on('MUD.m_user_id', '=', 'MU.id')
                    // ->join(['m_department', 'DEP'], 'left')->on('DEP.id', '=', 'MUD.m_department_id')
                    ->join(['m_approval_menu', 'MAM'], 'left')->on('MAM.m_user_id', '=', 'MU.id')
                    ->join(['m_authority', 'MA'], 'left')->on('MA.id', '=', 'MAM.m_authority_id')
                    ->and_where('MAM.m_menu_id', '=', $item['m_menu_id'])
                    ->and_where('MAM.petition_type', '=', $item['petition_type'])

                    ->where('MU.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where('MU.retirement_date', '>', $export_date)
                        ->or_where('MU.retirement_date', 'IS',\DB::expr('NULL'))
                    ->and_where_close()

                    ->and_where('MAM.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('MAM.enable_start_date'), \DB::expr('MAM.enable_end_date')])
                        ->or_where_open()
                            ->and_where(\DB::expr('MAM.enable_start_date'), '<=', $export_date)
                            ->and_where(\DB::expr('MAM.enable_end_date'), 'IS', \DB::expr('NULL'))
                        ->or_where_close()
                    ->and_where_close()

                    ->order_by('MAM.order', 'ASC')
                    ->group_by('MAM.m_user_id', 'MAM.m_authority_id')
                    ;
            $users = $query->execute()->as_array();  

            if(!empty($users)){
                $col = 3;
                foreach ($users as $user) {
                    $objPHPExcel->setActiveSheetIndex()->setCellValue(\PHPExcel_Cell::stringFromColumnIndex($col).$row,$user['fullname']);
                    $col++;
                    $objPHPExcel->setActiveSheetIndex()->setCellValue(\PHPExcel_Cell::stringFromColumnIndex($col).$row,$user['authority_name']);
                    $col++;
                }
            }

            $i++;
        }


        $format = ['alignment'=>array('horizontal'=>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,'wrap'=>true)];
        $objPHPExcel->getActiveSheet()->getStyle('A1:AC1')->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('A1:AC1')->getFill()->getStartColor()->setRGB('25a9cb');

        header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
        header("Cache-Control: max-age=0");
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="決裁経路（基準）-'.$export_date.'.xls"');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit;          
    }

    /*=============================================================
     * Author: Nguyen Anh Khoa
     * Action export list user
     *=============================================================*/
    public function action_list_approval_department_menu(){
        $param = \Input::param();
        $export_date = isset($param['export_date'])?date('Y-m-d', strtotime($param['export_date'])):date('Y-m-d');

        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->getProperties()->setCreator('Vision')
                                        ->setLastModifiedBy('Vision')
                                        ->setTitle('Office 2007 Document')
                                        ->setSubject('Office 2007 Document')
                                        ->setDescription('Document has been generated by PHP')
                                        ->setKeywords('Office 2007 openxml php')
                                        ->setCategory('Route File');

        $header = ['事業本部コード','事業本部','事業部コード','事業部','部門コード','部門','様式', '適用開始日', '適用終了日',
                    '第1 承認者','第1 承認者の権限',
                    '第2 承認者','第2 承認者の権限','第3 承認者','第3 承認者の権限',
                    '第4 承認者','第4 承認者の権限','第5 承認者','第5 承認者の権限',
                    '第6 承認者','第6 承認者の権限','第7 承認者','第7 承認者の権限',
                    '第8 承認者','第8 承認者の権限','第9 承認者','第9 承認者の権限',
                    '第10 承認者','第10 承認者の権限','第11 承認者','第11 承認者の権限',
                    '第12 承認者','第12 承認者の権限','第13 承認者','第13 承認者の権限',
                    '第14 承認者','第14 承認者の権限','第15 承認者','第15 承認者の権限',
                    ];
        $last_column = null;
        foreach($header as $i=>$v){
            $column = \PHPExcel_Cell::stringFromColumnIndex($i);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($column.'1',$v);
            $objPHPExcel->getActiveSheet()->getStyle($column.'1')
                ->applyFromArray([
                    'font' => [
                        'name' => 'Times New Roman',
                        'bold' => true,
                        'italic' => false,
                        'size' => 10,
                        'color' => ['rgb'=>  \PHPExcel_Style_Color::COLOR_WHITE]
                    ],
                    'alignment' => [
                        'horizontal' =>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                        'vertical' => \PHPExcel_Style_Alignment::VERTICAL_CENTER,
                        'wrap' => false
                    ]
                ]);
            switch($i+1){
                case 1:
                case 3:
                case 5:
                    $width = 10;
                    break;
                case 2:
                    $width = 18;
                    break;
                case 4:
                case 6:
                    $width = 30;
                    break;
                case 7:
                    $width = 50;
                    break;    
                case 11: case 13:
                case 15: case 17: case 19: case 21: case 23: case 25:
                case 27: case 29: case 31: case 33: case 35: case 37: case 39:
                    $width = 20;
                    break;
                default:
                    $width = 30;
                    break;
            }
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth($width);
            $last_column = $column;
        }
       
        /*====================================
         * Get list user has department enable_start_date >= export day <= enable_end_date
         * Or enable_start_date >= export day && enable_end_date IS NULL
         *====================================*/
        $query = \DB::select('MADM.*', \DB::expr('MM.name AS menu_name'), \DB::expr('MM.id AS menu_id'), 
                    \DB::expr('MRM.name AS request_menu_name'), \DB::expr('MRM.name AS request_menu_id'),
                    'MD.level')
                    ->from(['m_approval_department_menu', 'MADM'])
                    ->join(['m_department', 'MD'], 'left')->on('MD.id', '=', 'MADM.m_department_id')

                    ->join(['m_menu', 'MM'], 'left')->on('MM.id', '=', 'MADM.m_menu_id')
                        ->on('MADM.petition_type', '=', \DB::expr("1"))
                        ->on('MM.item_status', '=', \DB::expr("'active'"))->on('MM.enable_flg', '=', \DB::expr("1"))
                    ->join(['m_request_menu', 'MRM'], 'left')->on('MRM.id', '=', 'MADM.m_menu_id')
                        ->on('MADM.petition_type', '=', \DB::expr("2"))
                        ->on('MRM.item_status', '=', \DB::expr("'active'"))->on('MRM.enable_flg', '=', \DB::expr("1"))
                    ->where('MD.item_status', '=', 'active')

                    ->and_where('MADM.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('MADM.enable_start_date'), \DB::expr('MADM.enable_end_date')])
                        ->or_where_open()
                            ->and_where(\DB::expr('MADM.enable_start_date'), '<=', $export_date)
                            ->and_where(\DB::expr('MADM.enable_end_date'), 'IS', \DB::expr('NULL'))
                        ->or_where_close()
                    ->and_where_close()

                    ->group_by('MADM.m_department_id', 'MADM.m_menu_id', 'MADM.petition_type', 'MADM.enable_start_date')
                    ;
        $items = $query->execute()->as_array();
        
        //set content
        $i = 0;
        foreach($items as $item){
            $row = $i+2;
            
            switch ($item['petition_type']) {
                case 1:
                    $menu_name = $item['menu_name'];
                    $menu_id = $item['menu_id'];
                    break;
                case 2:
                    $menu_name = $item['request_menu_name'];
                    $menu_id = $item['request_menu_id'];
                    break;
            }
            if(empty($menu_id)) continue;


            //Get Full Name
            switch ($item['level']) {
                case 1:
                    //business
                    $depInfo = \Model_MDepartment::comboData(['m_department_id' => $item['m_department_id']], ['task' => 'business']);
                    break;
                case 2:
                    //division
                    $depInfo = \Model_MDepartment::comboData(['m_department_id' => $item['m_department_id']], ['task' => 'division']);
                    break;
                case 3:
                    //department
                    $depInfo = \Model_MDepartment::comboData(['m_department_id' => $item['m_department_id']], ['task' => 'department']);

                    break;
                
            }
            if(empty($depInfo)) continue;

            //Get user of routes
            $query = \DB::select('MU.fullname', \DB::expr('MA.name AS authority_name'))
                    ->from(['m_user', 'MU'])
                    ->join(['m_approval_department_menu', 'MADM'], 'left')->on('MADM.m_user_id', '=', 'MU.id')
                    ->join(['m_authority', 'MA'], 'left')->on('MA.id', '=', 'MADM.m_authority_id')
                    ->where('MU.item_status', '=', 'active')
                    ->and_where('MADM.item_status', '=', 'active')
                    ->and_where('MADM.m_department_id', '=', $item['m_department_id'])
                    ->and_where('MADM.m_menu_id', '=', $item['m_menu_id'])
                    ->and_where('MADM.petition_type', '=', $item['petition_type'])

                    ->where('MU.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where('MU.retirement_date', '>', $export_date)
                        ->or_where('MU.retirement_date', 'IS',\DB::expr('NULL'))
                    ->and_where_close()

                    ->and_where('MADM.item_status', '=', 'active')
                    ->and_where_open()
                        ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('MADM.enable_start_date'), \DB::expr('MADM.enable_end_date')])
                        ->or_where_open()
                            ->and_where(\DB::expr('MADM.enable_start_date'), '<=', $export_date)
                            ->and_where(\DB::expr('MADM.enable_end_date'), 'IS', \DB::expr('NULL'))
                        ->or_where_close()
                    ->and_where_close()

                    ->order_by('MADM.order', 'ASC')
                    ->group_by('MADM.m_user_id', 'MADM.m_authority_id')
                    ;

            //check valid date when level == 3
            if($item['level'] == 3){    
                $query->join(['m_department', 'DEP'], 'left')->on('DEP.id', '=', 'MADM.m_department_id')->on('DEP.level', '=', \DB::expr(3))
                        ->and_where('DEP.item_status', '=', 'active')
                        ->and_where_open()
                            ->and_where(\DB::expr("'{$export_date}'"), 'BETWEEN', [\DB::expr('DEP.enable_start_date'), \DB::expr('DEP.enable_end_date')])
                            ->or_where_open()
                                ->and_where(\DB::expr('DEP.enable_start_date'), '<=', $export_date)
                                ->and_where(\DB::expr('DEP.enable_end_date'), 'IS', \DB::expr('NULL'))
                            ->or_where_close()
                        ->and_where_close();
            }
            $users = $query->execute()->as_array();     
            
            if (empty($users)) continue;


            $business_code = isset($depInfo['business_code'])?$depInfo['business_code']:null;
            $business_name = isset($depInfo['business_name'])?$depInfo['business_name']:null;
            $division_code = isset($depInfo['division_code'])?$depInfo['division_code']:null;
            $division_name = isset($depInfo['division_name'])?$depInfo['division_name']:null;
            $department_code = isset($depInfo['department_code'])?$depInfo['department_code']:null;
            $department_name = isset($depInfo['deparment_name'])?$depInfo['deparment_name']:null;
            
            $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row, $menu_name);
            // \Vision_Common::system_format_date(strtotime($user['entry_date'])):null)
            $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row,$business_code)
                                            ->setCellValue('B'.$row,$business_name)
                                            ->setCellValue('C'.$row,$division_code)
                                            ->setCellValue('D'.$row,$division_name)
                                            ->setCellValue('E'.$row,$department_code)
                                            ->setCellValue('F'.$row,$department_name)
                                            ->setCellValue('G'.$row,$menu_name)
                                            ->setCellValue('H'.$row,$item['enable_start_date']?\Vision_Common::system_format_date(strtotime($item['enable_start_date'])):null)
                                            ->setCellValue('I'.$row,$item['enable_end_date']?\Vision_Common::system_format_date(strtotime($item['enable_end_date'])):null)
                                            ;

            if(!empty($users)){
                $col = 9;
                foreach ($users as $user) {
                    $objPHPExcel->setActiveSheetIndex()->setCellValue(\PHPExcel_Cell::stringFromColumnIndex($col).$row,$user['fullname']);
                    $col++;
                    $objPHPExcel->setActiveSheetIndex()->setCellValue(\PHPExcel_Cell::stringFromColumnIndex($col).$row,$user['authority_name']);
                    $col++;
                }
            }

            $i++;
        }

        $format = ['alignment'=>array('horizontal'=>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,'wrap'=>true)];
        $objPHPExcel->getActiveSheet()->getStyle('A1:AK1')->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('A1:AK1')->getFill()->getStartColor()->setRGB('25a9cb');

        header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
        header("Cache-Control: max-age=0");
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="決裁経路（カスタム）-'.$export_date.'.xls"');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit;          
    }


    /*=============================================================
     * Author: Hoang Phong Phu
     * Action export list form payment
     *=============================================================*/
    public function action_list_form_payment(){
        $param = \Input::param();
        $cids = [];
        if(isset($param['p'])){
            parse_str(base64_decode($param['p']), $params);
            $petition_id = isset($params['petition_id'])?$params['petition_id']:null;
            $cids = explode(',', $petition_id);
        }

        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->getProperties()->setCreator('Vision')
                                        ->setLastModifiedBy('Vision')
                                        ->setTitle('Office 2007 Document')
                                        ->setSubject('Office 2007 Document')
                                        ->setDescription('Document has been generated by PHP')
                                        ->setKeywords('Office 2007 openxml php')
                                        ->setCategory('Form Payment File');
        $header = ['No','申請日','申請番号','内容','件名','金額','領収書','申請者','状況','確認日','修正後金額','最新処理者','振込日'];

        $query = \DB::select('id','name')
                    ->from('m_petition_status');
        $m_petition_status = $query->execute()->as_array('id','name');

        foreach($header as $i=>$v){
            $column = \PHPExcel_Cell::stringFromColumnIndex($i);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($column.'1',$v);
            $objPHPExcel->getActiveSheet()->getStyle($column.'1')->applyFromArray($this->formatTitleHeader);
            switch($i+1){
                case 1:
                    $width = 8;
                    break;
                case 3:
                case 4:
                case 8:
                case 12:
                    $width = 25;
                    break;
                case 5:
                    $width = 80;
                    break;
                case 6:
                    $width = 15;
                    break;
                case 7:
                    $width = 12;
                    break;
                default:
                    $width = 20;
                    break;
            }
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth($width);
        }

        $i = $row = 0;
        foreach ($cids as $cid) {
            //======================== Begin Get Form From Other API ===============================
            $api_res = json_decode($this->rest->request('trequest/detail/' . $cid, 'get'));
            if($api_res->status == 'success'){
                $payment = $api_res->data;
                if(empty($payment)) continue;
                $mark = $payment->currency_symbol;
                $row = $i+2;

                $last_approval_user = null;
                foreach($payment->routes as $route){
                    if($route->m_user_id == $payment->last_approve_user_id){
                        $last_approval_user = $route->fullname;
                        break;
                    }
                }

                $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row,$i+1)
                                                    ->setCellValue('B'.$row,\Vision_Common::system_format_date(strtotime($payment->date)))
                                                    ->setCellValueExplicit('C'.$row,$payment->code,\PHPExcel_Cell_DataType::TYPE_STRING)
                                                    ->setCellValue('D'.$row,$payment->request_menu_name)
                                                    ->setCellValue('E'.$row,$payment->name)
                                                    ->setCellValue('F'.$row,$mark.number_format($payment->amount))
                                                    ->setCellValue('G'.$row,$payment->receipt_flg?'要':'不要')
                                                    ->setCellValue('H'.$row,$payment->user_create_form->fullname)
                                                    ->setCellValue('I'.$row,$m_petition_status[$payment->m_petition_status_id])
                                                    ->setCellValue('J'.$row,$payment->account_conf_date?\Vision_Common::system_format_date(strtotime($payment->account_conf_date)):null)
                                                    ->setCellValue('K'.$row,$mark.number_format($payment->cor_settlement_amount))
                                                    ->setCellValue('L'.$row,$last_approval_user)
                                                    ->setCellValue('M'.$row,$payment->transfer_date?\Vision_Common::system_format_date(strtotime($payment->transfer_date)):null);
                $i++;
            }
        }

        $format = ['alignment'=>array('horizontal'=>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,'wrap'=>true)];
        $objPHPExcel->getActiveSheet()->getStyle('A2:A'.$row)->applyFromArray($format);
        $objPHPExcel->getActiveSheet()->getStyle('B2:B'.$row)->applyFromArray($format);
        $objPHPExcel->getActiveSheet()->getStyle('G2:G'.$row)->applyFromArray($format);
        //set color title
        $objPHPExcel->getActiveSheet()->getStyle('A1:M1')->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('A1:M1')->getFill()->getStartColor()->setRGB('25a9cb');

        header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
        header("Cache-Control: max-age=0");
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="list-payment-'.date('Y-m-d').'.xls"');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit;
    }

    /*=============================================================
     * Author: Hoang Phong Phu
     * Action export list form 0.2 & 0.4
     *=============================================================*/
    public function action_list_form_process(){
        $params = [];
        $param = \Input::param();
        if(isset($param['p'])){
            parse_str(base64_decode($param['p']), $params);
        }

        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->getProperties()->setCreator('Vision')
                                        ->setLastModifiedBy('Vision')
                                        ->setTitle('Office 2007 Document')
                                        ->setSubject('Office 2007 Document')
                                        ->setDescription('Document has been generated by PHP')
                                        ->setKeywords('Office 2007 openxml php')
                                        ->setCategory('Form Process File');
        $header = ['コメント','優先度','状況','権限','判定','種別','件名','申請日','申請者','処理日','起案番号'];
        foreach($header as $i=>$v){
            $column = \PHPExcel_Cell::stringFromColumnIndex($i);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($column.'1',$v);
            $objPHPExcel->getActiveSheet()->getStyle($column.'1')->applyFromArray($this->formatTitleHeader);
            switch($i+1){
                case 6:
                    $width = 50;
                    break;
                case 7:
                    $width = 80;
                    break;
                case 8:
                case 10;
                    $width = 20;
                    break;
                case 9:
                    $width = 25;
                    break;
                case 11:
                    $width = 30;
                    break;
                default:
                    $width = 15;
                    break;
            }
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth($width);
        }
        //======================== Begin Get Form From Other API ===============================
        $url = 'system_formprocess/list_form?' . http_build_query($params);
        $api_res = json_decode($this->rest->request($url, 'get'));
        if($api_res->status == 'success'){
            $items = $api_res->data;
            $i = $row = 0;
            foreach($items as $item){
                $comment_flg = empty($item->comment_id) ? 'なし' : 'あり';
                $priority_flg = $item->priority_flg ? '優先' : '通常';
                $row = ($i+2);
                $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row, $comment_flg)
                                                ->setCellValue('B'.$row, $priority_flg)
                                                ->setCellValue('C'.$row, $item->petition_status_name)
                                                ->setCellValue('D'.$row, $item->authority_name)
                                                ->setCellValue('E'.$row, $item->approval_status_name)
                                                ->setCellValue('F'.$row, $item->menu_name)
                                                ->setCellValue('G'.$row, $item->name)
                                                ->setCellValue('H'.$row, \Vision_Common::system_format_date(strtotime($item->date)))
                                                ->setCellValue('I'.$row, $item->fullname)
                                                ->setCellValue('J'.$row, $item->last_approve_date ? \Vision_Common::system_format_date(strtotime($item->last_approve_date)):null)
                                                ->setCellValueExplicit('K'.$row, $item->code,\PHPExcel_Cell_DataType::TYPE_STRING);
                $i++;
            }

            $format = ['alignment'=>array('horizontal'=>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,'wrap'=>true)];
            $objPHPExcel->getActiveSheet()->getStyle('A2:A'.$row)->applyFromArray($format);
            $objPHPExcel->getActiveSheet()->getStyle('B2:B'.$row)->applyFromArray($format);
            $objPHPExcel->getActiveSheet()->getStyle('H2:H'.$row)->applyFromArray($format);
            $objPHPExcel->getActiveSheet()->getStyle('J2:J'.$row)->applyFromArray($format);
            //set color title
            $objPHPExcel->getActiveSheet()->getStyle('A1:K1')->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);
            $objPHPExcel->getActiveSheet()->getStyle('A1:K1')->getFill()->getStartColor()->setARGB('FF00CCFF');
        }

        header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
        header("Cache-Control: max-age=0");
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="Proposal-'.date('Y-m-d').'.xls"');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit;
    }


    /*=============================================================
     * Author: Nguyen Anh Khoa
     * Action export data form 0.4 - "交通費精算"
     * Input: start_date
     *=============================================================*/
    public function action_data_form_transportation_expenses_csv(){
        $params = [];
        $param = \Input::param();
        $start_date = isset($param['start_date'])?date('Y-m-d', strtotime($param['start_date'])):date('Y-m-d');
        $end_date = isset($param['end_date'])?date('Y-m-d', strtotime($param['end_date'])):date('Y-m-d');

        $start_month = isset($param['start_month'])?date('Y-m', strtotime($param['start_month'])):date('Y-m');
        $get_start_month = date('n', strtotime($start_month));
        $end_month = isset($param['end_month'])?date('Y-m', strtotime($param['end_month'])):date('Y-m');
        $get_end_month = date('n', strtotime($end_month));

        setlocale(LC_ALL, "en_US.UTF-8");


        while($get_start_month <= $get_end_month){
            $filePath = FILESPATH . '/' . '交通費精算-' . $start_month . '.csv';
            $handle = fopen($filePath, 'w+');
            fputs($handle, $bom =( chr(0xEF) . chr(0xBB) . chr(0xBF) ));
            $header = ['起案番号','所属部門名称','所属部門コード','社員番号','申請者','申請名称','申請日','件名','目的地','理由','優先度', '決裁経路変更', '状況',
                        '【金額】', '【仮払金額】', '【精算金額】', '使用日', '交通機関', '出発', '到着', '金額', '領収書'];

            fputcsv($handle, $header);            


            //======================== Begin Get Form From Other API ===============================

            $query = \DB::select('SM.id')
                            ->from(['t_request', 'SM'])
                            ->where('SM.m_request_menu_id', '=', 1)
                            ->and_where('SM.item_status', '=', 'active')
                            ->and_where('SM.date', 'LIKE', $start_month . '%')
                            ->order_by('SM.date', 'ASC');
            $arrForms = $query->execute()->as_array();
            if(!empty($arrForms)){
                $query = \DB::select('SM.id', 'SM.item')
                            ->from(['m_expense_item', 'SM'])
                            ->where('SM.type_code', '=', '01')
                            ->and_where('SM.item_status', '=', 'active');
                $expenseItemOption = $query->execute()->as_array('id', 'item');

                $query = \DB::select('SM.id', 'SM.item')
                            ->from(['m_expense_item', 'SM'])
                            ->where('SM.type_code', '=', '01')
                            ->and_where('SM.item_status', '=', 'active');
                $petitionStatusOption = $query->execute()->as_array('id', 'item');


                foreach ($arrForms as $val) {
                    $form_id = $val['id'];
                    $url = 'trequest/detail/' . $form_id;
                    $api_res = json_decode($this->rest->request($url, 'get'));
                    if($api_res->status == 'success'){
                        $item = $api_res->data;
                        // echo '<pre>';
                        // print_r($item);
                        // echo '</pre>';
                        // die;
                        if(!empty($item)){
                            
                            $code = $item->code;
                            $user_create_department_name = $item->user_create_form->department_name;
                            $user_create_department_code = $item->user_create_form->department_code;
                            $user_create_staff_no = $item->user_create_form->staff_no;
                            $user_create_fullname = $item->user_create_form->fullname;
                            $request_menu_name = $item->request_menu_name;
                            $date = $item->date;
                            $name = $item->name;
                            $destination = $item->destination;
                            $reason = $item->reason;

                            $priority_flg = ($item->priority_flg == 0)?'通常':'優先';
                            $change_route = ($item->change_route == 0)?'無':'有';
                            $m_petition_status_id = $item->m_petition_status_id;
                            $m_petition_status_name = $item->m_petition_status_name;
                            $amount = $item->amount;
                            $suspense_payments = $item->suspense_payments;
                            $settlement_amount = $item->settlement_amount;



                            $basicData = [$code, $user_create_department_name, $user_create_department_code, $user_create_staff_no,
                                        $user_create_fullname, $request_menu_name, $date, $name, $destination, $reason,
                                        $priority_flg, $change_route, $m_petition_status_name, $amount, $suspense_payments, $settlement_amount];
                            fputcsv($handle, $basicData);

                            $t_request_transport_spec = $item->t_request_transport_spec;
                            //Get Detail information
                            if(!empty($t_request_transport_spec)){
                                foreach ($t_request_transport_spec as $item_transport) {
                                    $detail_use_date = $item_transport->use_date;
                                    $detail_m_expense_item_id = $item_transport->m_expense_item_id;
                                    $detail_m_expense_item_id = @$expenseItemOption[$detail_m_expense_item_id];


                                    $departure_point = $item_transport->departure_point;
                                    $arrival_point = $item_transport->arrival_point;
                                    $transportation_spec_fee = $item_transport->transportation_spec_fee;
                                    $receipt_flg = ($item_transport->receipt_flg == 1)?'要':'不要';


                                    $basicData = ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''];
                                    $detailData = [$detail_use_date, $detail_m_expense_item_id, $departure_point, $arrival_point,
                                                    $transportation_spec_fee, $receipt_flg];

                                    fputcsv($handle, array_merge($basicData, $detailData));
                                }
                            }
                        }
                    }
                }
            }

            $start_month = date('Y-m', strtotime($start_month, '+1 month'));
            
            $get_start_month++;
        }
        fclose($handle);
        exit;
    }
    /*=============================================================
     * Author: Nguyen Anh Khoa
     * Action export data form 0.4 - "交通費精算"
     * Input: start_date
     *=============================================================*/
    public function action_data_form_transportation_expenses(){
        $params = [];
        $param = \Input::param();
        $start_date = isset($param['start_date'])?date('Y-m-d', strtotime($param['start_date'])):date('Y-m-d');
        $end_date = isset($param['end_date'])?date('Y-m-d', strtotime($param['end_date'])):date('Y-m-d');

        $objPHPExcel = new \PHPExcel();
        $objPHPExcel->getProperties()->setCreator('Vision')
                                        ->setLastModifiedBy('Vision')
                                        ->setTitle('Office 2007 Document')
                                        ->setSubject('Office 2007 Document')
                                        ->setDescription('Document has been generated by PHP')
                                        ->setKeywords('Office 2007 openxml php')
                                        ->setCategory('Form Process File');
        $header = ['起案番号','所属部門名称','所属部門コード','社員番号','申請者','申請名称','申請日','件名','目的地','理由','優先度', '決裁経路変更', '状況',
                    '【金額】', '【仮払金額】', '【精算金額】', '使用日', '交通機関', '出発', '到着', '金額', '領収書'];




        foreach($header as $i=>$v){
            $column = \PHPExcel_Cell::stringFromColumnIndex($i);
            $objPHPExcel->setActiveSheetIndex(0)->setCellValue($column.'1',$v);
            $objPHPExcel->getActiveSheet()->getStyle($column.'1')->applyFromArray($this->formatTitleHeader);
            $width = 20;
            $objPHPExcel->getActiveSheet()->getColumnDimension($column)->setWidth($width);
        }
        //======================== Begin Get Form From Other API ===============================

        $query = \DB::select('SM.id')
                        ->from(['t_request', 'SM'])
                        ->where('SM.m_request_menu_id', '=', 1)
                        ->and_where('SM.item_status', '=', 'active')
                        ->and_where('SM.date', 'BETWEEN', [$start_date, $end_date])
                        ->order_by('SM.date', 'ASC');
        $arrForms = $query->execute()->as_array();
        if(!empty($arrForms)){
            $i = $row = 2;
            foreach ($arrForms as $val) {
                $form_id = $val['id'];
                $url = 'trequest/detail/' . $form_id;
                $api_res = json_decode($this->rest->request($url, 'get'));
                if($api_res->status == 'success'){
                    $item = $api_res->data;
                    // echo '<pre>';
                    // print_r($item);
                    // echo '</pre>';
                    // die;
                    if(!empty($item)){
                        $row = $i;
                        
                        $code = $item->code;
                        $user_create_department_name = $item->user_create_form->department_name;
                        $user_create_department_code = $item->user_create_form->department_code;
                        $user_create_staff_no = $item->user_create_form->staff_no;
                        $user_create_fullname = $item->user_create_form->fullname;
                        $request_menu_name = $item->request_menu_name;
                        $date = $item->date;
                        $name = $item->name;
                        $destination = $item->destination;
                        $reason = $item->reason;
                        $priority_flg = $item->priority_flg;
                        $change_route = $item->change_route;
                        $m_petition_status_id = $item->m_petition_status_id;
                        $amount = $item->amount;
                        $suspense_payments = $item->suspense_payments;
                        $settlement_amount = $item->settlement_amount;

                        $objPHPExcel->setActiveSheetIndex()->setCellValue('A'.$row, $code)
                                                    ->setCellValue('B'.$row, $user_create_department_name)
                                                    ->setCellValue('C'.$row, $user_create_department_code)
                                                    ->setCellValue('D'.$row, $user_create_staff_no)
                                                    ->setCellValue('E'.$row, $user_create_fullname)
                                                    ->setCellValue('F'.$row, $request_menu_name)
                                                    ->setCellValue('G'.$row, $date)
                                                    ->setCellValue('H'.$row, $name)
                                                    ->setCellValue('I'.$row, $destination)
                                                    ->setCellValue('J'.$row, $reason)
                                                    ->setCellValue('K'.$row, $priority_flg)
                                                    ->setCellValue('L'.$row, $change_route)
                                                    ->setCellValue('M'.$row, $m_petition_status_id)
                                                    ->setCellValue('N'.$row, $amount)
                                                    ->setCellValue('O'.$row, $suspense_payments)
                                                    ->setCellValue('P'.$row, $settlement_amount)
                                                    ;

                        $t_request_transport_spec = $item->t_request_transport_spec;
                        //Get Detail information
                        if(!empty($t_request_transport_spec)){
                            foreach ($t_request_transport_spec as $item_transport) {
                                
                                $row = $i;
                                $detail_use_date = $item_transport->use_date;
                                $detail_m_expense_item_id = $item_transport->m_expense_item_id;
                                $departure_point = $item_transport->departure_point;
                                $arrival_point = $item_transport->arrival_point;
                                $transportation_spec_fee = $item_transport->transportation_spec_fee;
                                $receipt_flg = $item_transport->receipt_flg;

                                $objPHPExcel->setActiveSheetIndex()->setCellValue('Q'.$row, $detail_use_date)
                                                    ->setCellValue('R'.$row, $detail_m_expense_item_id)
                                                    ->setCellValue('S'.$row, $departure_point)
                                                    ->setCellValue('T'.$row, $arrival_point)
                                                    ->setCellValue('U'.$row, $transportation_spec_fee)
                                                    ->setCellValue('V'.$row, $receipt_flg)
                                                    ->setCellValue('W'.$row, $request_menu_name)
                                                    ;
                                $i++;
                            }
                            $i--;
                        }
                        $i++;
                    }
                }
            }
        }
        
        $format = ['alignment'=>array('horizontal'=>  \PHPExcel_Style_Alignment::HORIZONTAL_CENTER,'wrap'=>true)];
        $objPHPExcel->getActiveSheet()->getStyle('A1:V1')->getFill()->setFillType(\PHPExcel_Style_Fill::FILL_SOLID);
        $objPHPExcel->getActiveSheet()->getStyle('A1:V1')->getFill()->getStartColor()->setRGB('25a9cb');

        header("Last-Modified: ". gmdate("D, d M Y H:i:s") ." GMT");
        header("Cache-Control: max-age=0");
        header('Content-Type: application/vnd.ms-excel');
        header('Content-Disposition: attachment;filename="交通費精算-'.date('Y-m-d').'.xls"');
        $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        exit;
    }
}